plugins {
    id "de.undercouch.download" version "3.4.3"
}

apply plugin: 'cpp'
apply from: 'common.gradle'
apply plugin: 'de.undercouch.download'

def coverageEnabled = System.getenv('enableCoverage')
def target_system = System.getProperty('targetSystem') ?: 'centos9'
def buildType = System.getProperty('buildType') ?: 'release'

project.ext {
    platBuildDir = "${buildDir}/${osName}-${osArch}"
    modDepDir = "${platBuildDir}/module-dependencies"

    debug = (buildType != 'release')
    buildType = debug ? 'debug' : 'release'

    ansdkOsName = osName
    ansdkArch = (osArch == 'x86' ? 'i686' : osArch)
    gccArchFlag = (osArch == 'x86' ? '-m32' : '-m64')
    headSHA1 = "<dev>"

    try {
        def p = "git log -1 --pretty=%H".execute(null, new File("."))
        p.waitFor()
        headSHA1 = p.text.trim()
    } catch (e) {
        headSHA1 = System.getenv('HEAD_SHA')
    }

    def props = new Properties()
    props.load(new FileInputStream(file("version.properties")))
    moduleVersion = props.get("server-module-version")
    moduleRelease = props.get("release")
    cppSDKVersion = props.get("CPP-SDK-version")
    moduleName = "WebServer Module"
    buildTypeName = "Release Build"
    fullVersion = "${moduleName} ${moduleVersion} ${moduleRelease} ${headSHA1}: ${buildTypeName}"

    gypPath = "$projectDir/scripts/gyp/r1919/gyp"
    gypType = 'make'
    scriptExt = 'sh'
    sharedLibraryExt = 'so'

    nginxSupportedVersions = props.get("nginxSupportedVersions").split(',')

    libraryStageDir = "${platBuildDir}/opentelemetry-webserver-sdk"
    nginxStageDir = "${libraryStageDir}/WebServerModule/Nginx"

    coverageCompilerFlags = '-g -fprofile-arcs -ftest-coverage'
    coverageLinkerFlags = '-lgcov --coverage'
    libraryFlags = '-lrt -lpthread -ldl -lz -lcrypt'

    BOOST_INCLUDE = "${modDepDir}/boost/1.75.0/include"
    BOOST_LIB = "${modDepDir}/boost/1.75.0/lib/libboost_filesystem.a ${modDepDir}/boost/1.75.0/lib/libboost_system.a"
}

task extractANSDK(type: Copy) {
    from "dependencies"
    into modDepDir
}

task generateModuleVersionHeader(type: Copy) {
    group = 'SDK Library'
    description = 'Generate the module_version.h header'

    from "src/module_version_template.h"
    into "include/core"
    rename { "module_version.h" }
    expand(
        headSHA1: headSHA1,
        moduleVersion: moduleVersion,
        moduleRelease: moduleRelease,
        cppSDKVersion: cppSDKVersion,
        fullVersion: fullVersion
    )
}

task generateVersionFile(type: Copy) {
    group = 'SDK Library'
    description = 'Generate VERSION.txt'

    from "dist/VERSION.txt"
    into libraryStageDir
    expand(
        headSHA1: headSHA1,
        moduleVersion: moduleVersion,
        moduleRelease: moduleRelease,
        cppSDKVersion: cppSDKVersion,
        fullVersion: fullVersion
    )
}

task generateSources {
    dependsOn generateVersionFile, generateModuleVersionHeader
}

task gypLibrary(type: Exec) {
    group = 'SDK Library'
    description = 'Generate build scripts via gyp'

    dependsOn extractANSDK, generateSources
    inputs.file "src/build.gyp"
    outputs.file "${platBuildDir}/Makefile"

    ext.libraryBuildEnvironment = [
        ARCH_FLAG: gccArchFlag,
        ANSDK_DIR: modDepDir,
        COMPILER_FLAGS: (coverageEnabled) ? coverageCompilerFlags : '',
        LINKER_FLAGS: (coverageEnabled) ? coverageLinkerFlags : '',
        BOOST_LIB: BOOST_LIB,
        BOOST_INCLUDE: BOOST_INCLUDE,
        LIBRARY_FLAGS: libraryFlags,
        CPP_SDK_VERSION: cppSDKVersion,
    ]

    environment libraryBuildEnvironment
    workingDir 'src'
    commandLine gypPath, "--generator-output=${platBuildDir}", '--toplevel-dir=.', '--depth=./', '-f', gypType, 'build.gyp'
}

task buildLibrary(type: Exec) {
    group = 'SDK Library'
    description = 'Compile the SDK library'

    dependsOn gypLibrary
    inputs.property "buildType", buildType
    inputs.dir 'src/util'

    outputs.file "${platBuildDir}/out/Default/lib.target/libopentelemetry_webserver_sdk.so"
    args = ['make', 'V=1', '-j', Runtime.runtime.availableProcessors()]

    environment gypLibrary.libraryBuildEnvironment
    workingDir "${platBuildDir}"
    commandLine args
}

task stageLibrary(type: Copy) {
    group = 'SDK Library'
    description = 'Stage the SDK library distribution'

    doLast {
        file("${libraryStageDir}/logs").mkdirs()
    }

    from("dist/runSDKProxy.sh") { it.fileMode 0770 }
    from(buildLibrary) { it.into "sdk_lib/lib" }
    from("${modDepDir}/opentelemetry/${cppSDKVersion}/lib") {
        include "libopentelemetry_*.so"
        into "sdk_lib/lib"
    }
    from("dist/opentelemetry_sdk_log4cxx.xml.template") { it.into "conf" }
    from("dist/install.${scriptExt}") { it.fileMode 0700 }
    into libraryStageDir
}

task stripLibrary(type: Exec) {
    onlyIf { !debug }
    dependsOn stageLibrary
    workingDir "${libraryStageDir}/sdk_lib/lib"
    commandLine 'strip', '-x', "libopentelemetry_webserver_sdk.${sharedLibraryExt}"
}

task assembleLibrary(type: Tar) {
    group = 'SDK Library'
    dependsOn stripLibrary
    from stageLibrary
    baseName 'opentelemetry-webserver-sdk'
    into 'opentelemetry-webserver-sdk'
    destinationDir buildDir
    compression Compression.GZIP
}

//
// ------------- NGINX MODULE -------------
//
nginxSupportedVersions.each { nginxVersion ->
    task("downloadNginx${nginxVersion}", type: Download) {
        src "http://nginx.org/download/nginx-${nginxVersion}.tar.gz"
        dest buildDir
        overwrite false
    }

    task("extractNginx${nginxVersion}", type: Copy) {
        dependsOn "downloadNginx${nginxVersion}"
        from tarTree(resources.gzip("build/nginx-${nginxVersion}.tar.gz"))
        into buildDir
    }

    task("configureNginx${nginxVersion}", type: Exec) {
        group = 'Nginx Web Server Module'
        description = 'Run configure for Nginx OpenTelemetry Module'

        dependsOn "extractNginx${nginxVersion}"
        workingDir "${buildDir}/nginx-${nginxVersion}"
        commandLine './configure',
            "--with-compat",
            "--with-cc-opt=-Wno-error -Wno-unused-variable -Wno-unused-but-set-variable",
            "--with-ld-opt=-L${libraryStageDir}/sdk_lib/lib",
            "--add-dynamic-module=${projectDir}/src/nginx"
    }

    task("updateMakefile${nginxVersion}", type: Exec) {
        group = 'Nginx Web Server Module'
        description = 'Patch Makefile for dynamic build'
        commandLine 'bash', '-c', "src/nginx/script.sh ${buildDir}/nginx-${nginxVersion}/objs/Makefile"
    }

    task("buildNginxModule${nginxVersion}", type: Exec) {
        group = 'Nginx Web Server Module'
        description = 'Build Nginx OpenTelemetry module'

        dependsOn "configureNginx${nginxVersion}", stageLibrary, "updateMakefile${nginxVersion}"
        outputs.file "${buildDir}/nginx-${nginxVersion}/objs/ngx_http_opentelemetry_module.so"

        workingDir "${buildDir}/nginx-${nginxVersion}"
        commandLine 'make', 'modules'
    }

    task("stageNginxModule${nginxVersion}", type: Copy) {
        dependsOn "buildNginxModule${nginxVersion}"
        def nginxStageDirVersion = "${nginxStageDir}/${nginxVersion}"
        from "${buildDir}/nginx-${nginxVersion}/objs/ngx_http_opentelemetry_module.so"
        into nginxStageDirVersion
    }

    task("stripNginxModule${nginxVersion}", type: Exec) {
        onlyIf { !debug }
        dependsOn "stageNginxModule${nginxVersion}"
        workingDir "${nginxStageDir}/${nginxVersion}"
        commandLine 'strip', '-x', "ngx_http_opentelemetry_module.${sharedLibraryExt}"
    }
}

task assembleNginxModule(type: Tar) {
    group = 'Nginx Web Server Module'
    nginxSupportedVersions.each { nginxVersion ->
        dependsOn "stripNginxModule${nginxVersion}"
    }
    from libraryStageDir
    baseName "opentelemetry-webserver-sdk-${osArch}-${osName}"
    into 'opentelemetry-webserver-sdk'
    destinationDir file(buildDir)
    compression Compression.GZIP
}

task assembleWebServerModule(type: Tar) {
    group = 'Web Server Agent'
    description = 'Assemble final Web Server Agent artifact (tgz)'

    nginxSupportedVersions.each {
        nginxVersion ->
        dependsOn "stripNginxModule${nginxVersion}"
    }

    from libraryStageDir
    baseName "opentelemetry-webserver-sdk-${osArch}-${osName}"
    into 'opentelemetry-webserver-sdk'
    destinationDir file(buildDir)
    compression Compression.GZIP
}
