- name: start container & build
  run: |
    # Force override ENTRYPOINT and keep container alive
    docker run -idt \
      --entrypoint "" \
      --name apache_centos8_container \
      apache_centos8 \
      sleep infinity

    cd instrumentation/otel-webserver-module

    # clean working dir inside container
    docker exec apache_centos8_container bash -c \
      'cd /otel-webserver-module; rm -rf *;'

    # copy the repo into container
    docker cp . $(docker inspect --format="{{.Id}}" apache_centos8_container):/otel-webserver-module/

    # build inside container
    docker exec apache_centos8_container bash -c \
      'cd /otel-webserver-module; rm -rf build; \
       cp -r /dependencies /otel-webserver-module/; \
       cp -r /build-dependencies /otel-webserver-module/; \
       ./gradlew assembleWebServerModule'
